opening a pandas liberary

In [2]:
import pandas as pd

opening a locally csv file

In [4]:
df = pd.read_csv('../8.testingEnvironmentAndImportDataset/Dataset_spine.csv')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   pelvic incidence             310 non-null    float64
 1    pelvic tilt                 310 non-null    float64
 2    lumbar lordosis angle       310 non-null    float64
 3    sacral slope                310 non-null    float64
 4    pelvic radius               310 non-null    float64
 5    grade of spondylolisthesis  310 non-null    float64
 6   Class_att                    310 non-null    str
dtypes: float64(6), str(1)
memory usage: 17.1 KB
None

import from server

In [9]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])

df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0  sepal_length  sepal_width  petal_length  petal_width  species
1           5.1          3.5           1.4          0.2   setosa
2           4.9          3.0           1.4          0.2   setosa
3           4.7          3.2           1.3          0.2   setosa
4           4.6          3.1           1.5          0.2   setosa

index col parameter

In [10]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],index_col=0)

df.head()

              sepal_width  petal_length  petal_width  species
sepal_length
sepal_length  sepal_width  petal_length  petal_width  species
5.1                   3.5           1.4          0.2   setosa
4.9                   3.0           1.4          0.2   setosa
4.7                   3.2           1.3          0.2   setosa
4.6                   3.1           1.5          0.2   setosa

useColumns paramter

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,usecols=['sepal_length'])

df.head()

   sepal_length
0           5.1
1           4.9
2           4.7
3           4.6
4           5.0

In [18]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],skiprows=[0,1])

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           4.9          3.0           1.4          0.2  setosa
1           4.7          3.2           1.3          0.2  setosa
2           4.6          3.1           1.5          0.2  setosa
3           5.0          3.6           1.4          0.2  setosa
4           5.4          3.9           1.7          0.4  setosa

nrows

In [21]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,header=0,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],nrows=2)

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [ ]:
import pandas as pd

url = "zomato.csv"

df = pd.read_csv(url,encoding='latin-1')

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

skip bad lines

In [ ]:
df = pd.read_csv('../8.testingEnvironmentAndImportDataset/Dataset_spine.csv',error_bad_lines=False)
print(df.head())

           pelvic incidence   pelvic tilt   lumbar lordosis angle  \
63.027817         22.552586     39.609117               40.475232
39.056951         10.060991     25.015378               28.995960
68.832021         22.218482     50.092194               46.613539
69.297008         24.652878     44.311238               44.644130
49.712859          9.652075     28.317406               40.060784

            sacral slope   pelvic radius  grade of spondylolisthesis  \
63.027817      98.672917       -0.254400                    Abnormal
39.056951     114.405425        4.564259                    Abnormal
68.832021     105.985135       -3.530317                    Abnormal
69.297008     101.868495       11.211523                    Abnormal
49.712859     108.168725        7.918501                    Abnormal

           Class_att
63.027817      101.0
39.056951        NaN
68.832021        NaN
69.297008        NaN
49.712859        NaN

dtypes

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],header=0,dtype={"sepal_length": float})

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

converters

In [50]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
def rename_columns(column_name):
    return column_name.upper()
df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],header=0,converters={'species':rename_columns})

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  SETOSA
1           4.9          3.0           1.4          0.2  SETOSA
2           4.7          3.2           1.3          0.2  SETOSA
3           4.6          3.1           1.5          0.2  SETOSA
4           5.0          3.6           1.4          0.2  SETOSA

Na_Values Paramter

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url,names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'],na_values=['NA','?','1.3'])

df.head()